### ISSUE TITLE
Test the jobs using japa or any other test runner.

### ISSUE THREAD

**Issue by sayeed205** [shiny/adonis-resque#4]
Hey there,

I am here again ;).

How do I test the jobs using japa or any other test runner.

**Comment by shiny** [comment]
`perform` method could return a value to `assert`.
Also, you can fake & mock dependency serivces by `app.container.swap`.
This document might be useful: https://docs.adonisjs.com/guides/testing/mocks-and-fakes

**Comment by sayeed205** [comment]
Okay I was thinking that if we can manually call the `perform`  function in a test file and we can either assert or just check if the function ran successfully without any error.

**Comment by shiny** [comment]
> Okay I was thinking that if we can manually call the `perform` function in a test file and we can either assert or just check if the function ran successfully without any error.

Sure, we can. Just be careful only if you enqueue another job in a job. 
Maybe we should provide some `mock` or `fake` method in that case.
