### ISSUE TITLE
Adonis redis@9.x.x - install fails with `node ace add adonis-resque`

### ISSUE THREAD

**Issue by akatora28** [shiny/adonis-resque#6]
Is this compatible with the 9.x.x versions of `@adonisjs/redis`? I hit an error: 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myproject@0.0.0
npm ERR! Found: @adonisjs/redis@9.1.0
npm ERR! node_modules/@adonisjs/redis
npm ERR!   @adonisjs/redis@"^9.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @adonisjs/redis@"^8.0.1" from adonis-resque@1.2.3
npm ERR! node_modules/adonis-resque
npm ERR!   adonis-resque@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I was able to resolve by rolling back to `^8.0.1`, but wasn't sure if this is just an issue of the dependency version number needing to be changed in this package, or if there's actual breaking changes that'll need a PR to fix. 

If I have some time to test out I'll take a look and see, but just wanted to flag in case anyone else comes across the issue.

**Comment by shiny** [comment]
Thank you for the report. I will plan to update all dependent packages to the latest.
```
npm outdated
Package              Current   Wanted  Latest  Location                          Depended by
@adonisjs/assembler    7.5.1    7.7.0   7.7.0  node_modules/@adonisjs/assembler  adonis-resque
@adonisjs/core         6.8.0   6.12.1  6.12.1  node_modules/@adonisjs/core       adonis-resque
@adonisjs/redis        8.0.1    8.0.1   9.1.0  node_modules/@adonisjs/redis      adonis-resque
@japa/expect-type      2.0.1    2.0.1   2.0.2  node_modules/@japa/expect-type    adonis-resque
@japa/runner           3.1.2    3.1.2   3.1.4  node_modules/@japa/runner         adonis-resque
@types/node          20.12.2  20.16.1  22.5.0  node_modules/@types/node          adonis-resque
croner                 8.0.1    8.1.1   8.1.1  node_modules/croner               adonis-resque
eslint                8.57.0   8.57.0   9.9.0  node_modules/eslint               adonis-resque
nock                  13.5.4   13.5.5  13.5.5  node_modules/nock                 adonis-resque
node-resque            9.3.3    9.3.5   9.3.5  node_modules/node-resque          adonis-resque
tsup                   8.0.2    8.2.4   8.2.4  node_modules/tsup                 adonis-resque
typescript             5.4.3    5.5.4   5.5.4  node_modules/typescript           adonis-resque
```

**Comment by akatora28** [comment]
Thanks for the quick reply! I'll keep an eye out for the update when it comes through and test out in my project as I have time. Appreciate all your work on the package!

**Comment by shiny** [comment]
Unfortunately the latest adonis logger in @adonisjs/core would cause job progress quit unexpectedly.
So I have to publish an update that isn't backward compatible. You can try 

```bash
npm i adonis-resque@2.0.0-alpha.0
node ace configure adonis-resque
```

About the changes, referer to [migration from v1 to v2](https://github.com/shiny/adonis-resque?tab=readme-ov-file#migration-from-v1-to-v2)

**Comment by akatora28** [comment]
Sorry, didn't realize how involved this fix was gonna end up being for you, reopening the issue quickly.

Thanks for the heads up on v1 to v2 changes, I went ahead and installed the alpha version and have my app running in dev. I still have to test out a job or two here, but it's looking good so far on my end, once again really appreciate all your work on this!
