### ISSUE TITLE
`E_CANNOT_GENERATE_URL` `E_CANNOT_LOOKUP_ROUTE` in background jobs using adonis-resque

### ISSUE THREAD

**Issue by sayeed205** [shiny/adonis-resque#7]
```ts
const fileKey = `products/images/${cuid()}.jpeg`
await drive.use().put(fileKey, resizedImage, {
   contentType: 'image/jpeg',
})
const savedImageUrl = await drive.use().getUrl(fileKey)
```
The above code is in a job and When I am running the job in same thread as the web server it works fine but If I run the job in diff thread/process I am getting error as follows -
![image](https://github.com/user-attachments/assets/6e930f4d-3f7b-49a9-abe6-49f6ffdb870b)

I asked the same in [adonis discord server](https://discordapp.com/channels/423256550564691970/1293581863536955462) and according to  [Romain Lanz](https://github.com/RomainLanz) `The package author probably forgot to commit the router when running the command`

**Comment by shiny** [comment]
I can reproduce this issue, but I'm not entirely sure what he means.

**Comment by shiny** [comment]
After going through his code, I understand now. https://github.com/RomainLanz/adonis-bull-queue/blob/d282517c867b07ae8e5e69230136194419cc2180/commands/queue_listener.ts#L27
let me try to fix it.

**Comment by shiny** [comment]
Version 2.0.1 published.

**Comment by sayeed205** [comment]
Thanks

**Comment by jdemangeon** [comment]
Hi @shiny ! For your information, all my routes are 404 (checked `node ace list:routes` and they are listed, but not working) since i updated to this version. The previous one (alpha from the README) is working well.

Can give more information if needed ;) 

Thanks a lot for your work!

**Comment by shiny** [comment]
> Hi @shiny ! For your information, all my routes are 404 (checked `node ace list:routes` and they are listed, but not working) since i updated to this version. The previous one (alpha from the README) is working well.
> 
> Can give more information if needed ;)
> 
> Thanks a lot for your work!

Thank you for your report. I have unpublished version 2.0.1 due to emergency. Router should not commit in web environments, which is an oversight. I plan to fix it tomorrow.
