### ISSUE TITLE
adonis-resque fails to start on Railway

### ISSUE THREAD

**Issue by Fawwaz-2009** [shiny/adonis-resque#8]
Hey all 👋  , I'm using adonis-resque package and it keeps failing on start. 

 I'm guessing it's some kind of race condition, because if I just disabled `runWorkerInWebEnv: false` and then after the server is fully running I run `node ace resque:start`

but probably the weirdest thing that even-though my app is dockerized and works just fine locally even when using prod envs, somehow in prod on railway it fails the build!.

![image](https://github.com/user-attachments/assets/c0cfc7a0-fe80-4766-9ad6-3f1aa4e5bed6)

**Comment by shiny** [comment]
Thank you for your report. 
This seems to be a Redis connection issue.
Since I haven't a Railway account yet, I'm unable to reproduce the issue at the moment.

**Comment by Fawwaz-2009** [comment]
thanks @shiny , I managed to solve the issue and leaving the solution here just in case it can help someone in the future.
Inside your redis config you want to make sure that `tls=undefined` and `family=0`
